version: '3'
services:
  python3:
    restart: always
    build:
      context: .
      dockerfile: DockerfileForPython
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./workplace:/root/workplace
  gcc-cpp:
    image: 'gcc:9.2.1'
    container_name: 'gcc'
    build:
      context: .
      dockerfile: DockerfileForCpp
    volumes:
      - ./workplace:/root/workplace
    working_dir: '/root/'
    tty: true