version: '3'
services:
  python3:
    restart: always
    build:
      context: .
      dockerfile: DockerfileForPython
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./workplace:/root/workplace